name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  lint_commit:
    name: Lint commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run commit lint
        run: npx commitlint --from="$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})"

  check_code:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run Pint
        run: vendor/bin/pint --test

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=2G
  
  test_code:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: clover.xml
          flags: pull-request
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
