name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'DEPENDENCIES.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate a token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private_key: ${{ secrets.SEMANTIC_RELEASE_KEY_PEM }}

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Generate dependencies
        run: |
          chmod +x dependencies.sh
          ./dependencies.sh

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }}.git
          git add DEPENDENCIES.md
          git commit -m "chore(release): auto-generate dependencies" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Pull latest remote changes
        run: git pull origin main

      - name: Generate a token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private_key: ${{ secrets.SEMANTIC_RELEASE_KEY_PEM }}
          
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        with:
          semantic_version: 22.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
