name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'DEPENDENCIES.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Generate a token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private_key: ${{ secrets.SEMANTIC_RELEASE_KEY_PEM }}
      - name: Set up Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Install Node.js dependencies
        run: npm ci
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: curl, fileinfo, imagick, imap, json, pdo
      - name: Install PHP dependencies
        run: composer install
      - name: Generate dependencies
        run: |
          chmod +x dependencies.sh
          ./dependencies.sh
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): auto-generate dependencies"
          commit_user_name: "semantic-release-bot"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          branch: main
          file_pattern: DEPENDENCIES.md
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Generate a token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private_key: ${{ secrets.SEMANTIC_RELEASE_KEY_PEM }}
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-release
        with:
          semantic_version: 22.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
